### ISSUE TITLE
Add a fallback for deleted users

### ISSUE THREAD

**Issue by Eldenroot** [inferno211/Groupimage-to-label-text#4]
When you delete a user and leave its posts/threads, this user has no gid ID, so the output is something like this

![image](https://user-images.githubusercontent.com/778890/44543584-3d073d00-a710-11e8-9fe8-ddacdf170ede.png)

![image](https://user-images.githubusercontent.com/778890/44543605-4b555900-a710-11e8-94f5-a18fff8b8232.png)

@inferno211

**Comment by inferno211** [comment]
Fixed, thanks ;)
